- Fix compilation warnings + code smells - Setup scapegoat - Update CI configuration

diff --git a/.github/workflows/scala.yml b/.github/workflows/scala.yml
--- a/.github/workflows/scala.yml
+++ b/.github/workflows/scala.yml
@@ -17,5 +17,19 @@ jobs:
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
+
+    - name: 'Check code quality'
+      run: |
+        sbt ';scalafixAll -check ;scalariformFormat ;test:scalariformFormat'
+        
+        git diff --exit-code || (
+          echo "ERROR: Scalariform check failed, see differences above."
+          echo "To fix, format your sources using ./build scalariformFormat test:scalariformFormat before submitting a pull request."
+          echo "Additionally, please squash your commits (eg, use git commit --amend) if you're going to update this pull request."
+          false
+        )
+        
+        sbt scapegoat
+
     - name: Run tests
       run: sbt ';+core/testOnly ;^sbt-plugin/testOnly'
